### ISSUE TITLE
User can see their car.

### ISSUE THREAD

**Issue by michaelvalenzuela** [michaelvalenzuela/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List
- [x] Create HTML skeleton
- [x] Add favicon to title
- [x] Create a simple background using HTML and CSS
- [x] Place F1 image found in starting files in html
- [x] Position F1 image at the top right
- [x] Make sure user can see the car
- [x] Delete all unnecessary CSS
- [x] Fix any bugs
- [x] Test
