### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by michaelvalenzuela** [michaelvalenzuela/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Listen for 'keydown' event
- [x] Modify style property of car img to transform based on key
- [x] Delete any unused CSS
- [x] Fix any bugs
- [x] Test
