### ISSUE TITLE
User can start their car.

### ISSUE THREAD

**Issue by michaelvalenzuela** [michaelvalenzuela/driving-game#4]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Create a data model called "car"
- [x] Add a "location" property to "car" to hold x and y position values
- [x] Add absolute property to the car
- [x] Create a function to move the car
- [x] Add style to change top and left box offset styles 
- [x] setInteval for 16 miliseconds
- [x] Verify car is moving in a straight line
- [x] Fix all bugs
- [x] Remove unused CSS
- [x] Test functionality again
