### ISSUE TITLE
User can stop their car.

### ISSUE THREAD

**Issue by michaelvalenzuela** [michaelvalenzuela/driving-game#5]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add a property "isStarted" to "car" data model
- [x] Assign default  value of property "isStarted" to false
- [x] Create a function called "stopCar"
- [x] add clearInterval() to stopCar function
- [x] Change property "isStarted" to false
- [x] Listen for "keydown" event with key "Space" and assign callback function as "stopCar"
- [x] Verify car stops
- [x] Fix all bugs
- [x] Test features again
