### ISSUE TITLE
User can steer their car.

### ISSUE THREAD

**Issue by michaelvalenzuela** [michaelvalenzuela/driving-game#6]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Create a move function
- [x] Create moveX and moveY properties within car to tell which direction it moves
- [x] Update move properties of car based on arrow key
- [x] Verify car is moving as wanted
- [x] Fix bugs
- [x] Test again
